try debug

diff --git a/.github/workflows/run_tests.yml b/.github/workflows/run_tests.yml
--- a/.github/workflows/run_tests.yml
+++ b/.github/workflows/run_tests.yml
@@ -1,4 +1,4 @@
-# .github/worklows/run_tests.yml
+# .github/workflows/run_tests.yml
 
 # whenever push, do the tests
 on:
@@ -13,10 +13,6 @@ jobs:
 
     # test on linux
     runs-on: 'ubuntu-latest'
-
-    defaults:
-      run:
-        working-directory: .
 
     # Python version that coded in and more recent version
     strategy:
@@ -45,7 +41,17 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
-        
+      
+
+      - name: inspect repo
+        run: |
+          echo "Current dir:"
+          pwd
+          echo "Contents:"
+          ls -la
+          echo "Src contents:"
+          ls -la src || echo "src not found"
+          
         # now to clean and ingest data, train model and 
       - name: get data and train models
         run: |
@@ -65,10 +71,6 @@ jobs:
   # test on linux only for now
       runs-on: ubuntu-latest
 
-      defaults:
-      run:
-        working-directory: .
-      
       steps:
   # first clone the repo into the runner's VM
       - uses: actions/checkout@v5
